### ISSUE TITLE
Add SSH

### ISSUE THREAD

**Issue by nk027** [fineprint-global/docker-rstudio#3]
Is it possible to add SSH so I can access my GitHub account through that?

(Moved from <https://github.com/fineprint-global/rstudio>)

**Comment by vwmaus** [comment]
Do you really need that? You have a terminal on Rstudio, you can login with user fineprint. However, it would be good to add the dependencies to the image not install on the container, otherwise, they will be lost on eventual restarts.

**Comment by vwmaus** [comment]
ssh added to the image
