### ISSUE TITLE
Include a Rprofile.site to use CRAN as default repo

### ISSUE THREAD

**Issue by Gutschlhofer** [fineprint-global/docker-rstudio#8]
Currently, it's set to a MRAN snapshot mirror, leading to packages not being up-to-date or not updateable if you do not specify a specific repository.

```
> getOption("repos")
                                            CRAN 
"https://mran.microsoft.com/snapshot/2019-02-02" 
```

**Comment by Gutschlhofer** [comment]
For now, we can include the following in our `.First()` function in the `.Rprofile`:

```R
options(repos = "https://cran.rstudio.com/")
```

**Comment by vwmaus** [comment]
@nk027 can you also incorporate this?

**Comment by nk027** [comment]
@vwmaus That's already done in the rstudio repo, see also <https://github.com/fineprint-global/rstudio/pull/15>
